image: node:18.17.1
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: pnpm
    paths:
      - node_modules/
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install
    - pnpm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
